name: testing

on: 
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Test parser library
        run: |
          echo $ cd test
          cd test
          echo $ node parser.js        
          node parser.js
      

